# Deploy using gitflow
#
# Basic idea:
# * Developers almost always push to main first.
# * Releases happen on a branch
# * They can cherry-pick (or ffwd-merge, aka no-fault rebase) to releases
# * Once a release goes out it is tagged. Tags are on releases, these may or
#   may not be in a history.
#
# Where do deployments go:
# main -> develop01
# feature/* -> develop[X] after select
# release/* -> staging
# v* -> production after block & shout

env:
  AWS_ACCOUNT_ALIAS: common
  ENVIRONMENT_NAME: common
  DEPLOY_ENVIRONMENT_NAME: production
  TEST_ENVIRONMENT_NAME: production
  S3_HOSTNAME: demos.developer.virtru.com
  USE_NODE_16: true

steps:
  - label: ':gear: build & unit test'
    commands:
      - buildkite-agent pipeline upload .buildkite/pr.yml
