env:
  USE_NODE_18: true
  NODE_VERSION: "$(cat .nvmrc)"

steps:
  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"

  - wait

  - label: ":mag: Run unit tests"
    command: "buildkite-scripts/scripts/npm-test.sh"
    key: "unit-tests"
    depends_on: "dependency"

  - label: ":docker: Run App"
    command:
      - |
        docker build -t pt:latest .
        docker run -p 443:3000 pt:latest
    key: "docker"
    depends_on: "dependency"

  - wait

  - label: ":npm: e2e Tests"
    command: "buildkite-scripts/scripts/npm.sh run playwright-test"
    key: "e2e-test"
    depends_on: "docker"
