env:
  USE_NODE_18: true
  NODE_VERSION: "$(cat .nvmrc)"

steps:
  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"


#  - label: ":mag: Setup host"
#    command: "echo \"127.0.0.1		local.virtru.com\" | sudo tee --append /etc/hosts"
#    depends_on: "dependency"
#    key: "host"

  - label: ":mag: Run unit tests"
    command: "buildkite-scripts/scripts/npm-test.sh"
    key: "unit-tests"
    depends_on: "dependency"

  - label: ":mag: Docker Build"
    command: "docker build . -t pt:latest && docker run --name protect-and-track --add-host=local.virtru.com:127.0.0.1 -it pt:latest"
    key: "docker"
    depends_on: "dependency"
    plugins:
      - docker#v5.8.0:

  - wait

  - label: ":mag: Docker Exec"
    command: "docker exec -it protect-and-track sh npm run playwright-test"
    key: "docker-exec"
    depends_on: "docker"
    plugins:
      - docker#v5.8.0:

#  - wait
#
#  - label: ":npm: e2e Tests"
#    command: "buildkite-scripts/scripts/npm.sh run playwright-test"
#    key: "e2e-test"
#    depends_on: "docker"
