env:
  USE_NODE_16: true
  NODE_VERSION: "$(cat .nvmrc)"

steps:
  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"

  - wait

  - label: ":npm: :lock: NPM Audit"
    command: "buildkite-scripts/mars/wrap/npm-audit.sh"
    key: "dependency-audit"
    depends_on: "dependency"

  - wait

  - label: ":mag: Run unit tests"
    command: "buildkite-scripts/scripts/npm-test.sh"
    key: "unit-tests"
    depends_on: "dependency"
