env:
  USE_NODE_18: true
  NODE_VERSION: "$(cat .nvmrc)"

steps:
  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"


#  - label: ":mag: Setup host"
#    command: "echo \"127.0.0.1		local.virtru.com\" | sudo tee --append /etc/hosts"
#    depends_on: "dependency"
#    key: "host"

  - label: ":mag: Run unit tests"
    command: "buildkite-scripts/scripts/npm-test.sh"
    key: "unit-tests"
    depends_on: "dependency"

  - label: ":mag: Run e2e tests"
    command: "echo '127.0.0.1 local.virtru.com' | sudo tee -a /etc/hosts"
    key: "docker"
    depends_on: "dependency"
#    plugins:
#      - docker-compose#v3.0.3:
#          run: front

#  - wait
#
#  - label: ":npm: e2e Tests"
#    command: "buildkite-scripts/scripts/npm.sh run playwright-test"
#    key: "e2e-test"
#    depends_on: "docker"
