env:
  USE_NODE_16: true

steps:
#  - label: ':npm: :lock: NPM Audit'
#    command: '.buildkite/scripts/npm-audit.sh'

  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"

  - label: ":mag: Run unit tests"
    command: "buildkite-scripts/scripts/npm-test.sh"
    key: "unit-tests"
    depends_on: "dependency"
