env:
  USE_NODE_16: true

steps:

  - label: ":hammer: :git: version"
    key: "version"
    command: '.buildkite/scripts/git-version.sh'

  - label: ":npm: Install Dependencies (CI)"
    command: "buildkite-scripts/mars/wrap/npm-ci.sh"
    key: "dependency"

